### ISSUE TITLE
vicuna-13b-GPTQ-4bit-128g.ipynb seems to have dep conflict

### ISSUE THREAD

**Issue by hchiam** [camenduru/text-generation-webui-colab#10]
Not sure what I'm doing wrong, but it seems `transformers` might have conflicting version numbers, or `PIL.Image.Resampling` isn't available for some reason.

Running https://colab.research.google.com/github/camenduru/text-generation-webui-colab/blob/main/vicuna-13b-GPTQ-4bit-128g.ipynb gave me output that ends with:

```txt
Status Legend:
(OK):download completed.
/content/text-generation-webui
Traceback (most recent call last):
  File "/content/text-generation-webui/server.py", line 18, in <module>
    from modules import api, chat, shared, training, ui
  File "/content/text-generation-webui/modules/api.py", line 6, in <module>
    from modules.text_generation import generate_reply
  File "/content/text-generation-webui/modules/text_generation.py", line 7, in <module>
    import transformers
ModuleNotFoundError: No module named 'transformers'
```

which I've traced to the last line `!python server.py --share --chat --wbits 4 --groupsize 128`

Running the following in a new code block (no version numbers) to address missing deps didn't seem to get me very far either:

```txt
!pip install transformers accelerate datasets peft safetensors SentencePiece
!python server.py --share --chat --wbits 4 --groupsize 128
```

still gave me this error:

```txt
AttributeError: module 'PIL.Image' has no attribute 'Resampling'
```

Other references:

https://github.com/camenduru/text-generation-webui/blob/main/requirements.txt

https://github.com/camenduru/text-generation-webui/blob/main/server.py

**Comment by camenduru** [comment]
thanks for the info @hchiam  ❤ please try again
