### ISSUE TITLE
Trying to put an image at the character but it fail

### ISSUE THREAD

**Issue by iDarknessSam** [camenduru/text-generation-webui-colab#13]
Hello! I'm using the colab version of this and i'm trying to import an image to the character but nothing seens to works for some reason, i'm trying to do this for a while but I don't know why is giving me so many erros! can someone help me to solve this?
![Screenshot_20230615_185530](https://github.com/camenduru/text-generation-webui-colab/assets/59544278/f116d1ef-ebed-46ff-bf16-17418faabbfe)
![Screenshot_20230615_185553](https://github.com/camenduru/text-generation-webui-colab/assets/59544278/2e36a610-a2f0-4df1-b395-91b086eb1515)

**Comment by camenduru** [comment]
thanks for the info @iDarknessSam  ❤ please try again
