### ISSUE TITLE
[Bug]: OS Error: No file named pytorch_model.bin

### ISSUE THREAD

**Issue by Cabel7** [camenduru/text-generation-webui-colab#15]
I'm getting an os error 
No file named pytorch_model.bin in directory models
when running text generation webui: 
stable-vicuna-13B-GPTQ-4bit-128g

Notebook
%cd /content
!apt-get -y install -qq aria2

!git clone -b v1.7 https://github.com/camenduru/text-generation-webui
%cd /content/text-generation-webui
!pip install -r requirements.txt
!pip install -U gradio==3.28.3

!mkdir /content/text-generation-webui/repositories
%cd /content/text-generation-webui/repositories
!git clone -b v1.2 https://github.com/camenduru/GPTQ-for-LLaMa.git
%cd GPTQ-for-LLaMa
!python setup_cuda.py install

!aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://huggingface.co/4bit/stable-vicuna-13B-GPTQ/raw/main/config.json -d /content/text-generation-webui/models/stable-vicuna-13B-GPTQ -o config.json
!aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://huggingface.co/4bit/stable-vicuna-13B-GPTQ/raw/main/generation_config.json -d /content/text-generation-webui/models/stable-vicuna-13B-GPTQ -o generation_config.json
!aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://huggingface.co/4bit/stable-vicuna-13B-GPTQ/raw/main/special_tokens_map.json -d /content/text-generation-webui/models/stable-vicuna-13B-GPTQ -o special_tokens_map.json
!aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://huggingface.co/4bit/stable-vicuna-13B-GPTQ/resolve/main/tokenizer.model -d /content/text-generation-webui/models/stable-vicuna-13B-GPTQ -o tokenizer.model
!aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://huggingface.co/4bit/stable-vicuna-13B-GPTQ/raw/main/tokenizer_config.json -d /content/text-generation-webui/models/stable-vicuna-13B-GPTQ -o tokenizer_config.json
!aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://huggingface.co/4bit/stable-vicuna-13B-GPTQ/resolve/main/stable-vicuna-13B-GPTQ-4bit.compat.no-act-order.safetensors -d /content/text-generation-webui/models/stable-vicuna-13B-GPTQ -o stable-vicuna-13B-GPTQ-4bit.compat.no-act-order.safetensors

%cd /content/text-generation-webui
!python server.py --share --chat --wbits 4 --groupsize 128

Output

/content/text-generation-webui
2023-07-12 06:36:29 INFO:Unwanted HTTP request redirected to localhost :)
2023-07-12 06:36:32 WARNING:The gradio "share link" feature uses a proprietary executable to create a reverse tunnel. Use it with care.
2023-07-12 06:36:35.091770: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
bin /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda118.so
2023-07-12 06:36:38 INFO:Loading stable-vicuna-13B-GPTQ...
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /content/text-generation-webui/server.py:1154 in <module>                    │
│                                                                              │
│   1151 │   │   update_model_parameters(model_settings, initial=True)  # hija │
│   1152 │   │                                                                 │
│   1153 │   │   # Load the model                                              │
│ ❱ 1154 │   │   shared.model, shared.tokenizer = load_model(shared.model_name │
│   1155 │   │   if shared.args.lora:                                          │
│   1156 │   │   │   add_lora_to_model(shared.args.lora)                       │
│   1157                                                                       │
│                                                                              │
│ /content/text-generation-webui/modules/models.py:74 in load_model            │
│                                                                              │
│    71 │   │   │   │   return None, None                                      │
│    72 │                                                                      │
│    73 │   shared.args.loader = loader                                        │
│ ❱  74 │   output = load_func_map[loader](model_name)                         │
│    75 │   if type(output) is tuple:                                          │
│    76 │   │   model, tokenizer = output                                      │
│    77 │   else:                                                              │
│                                                                              │
│ /content/text-generation-webui/modules/models.py:144 in huggingface_loader   │
│                                                                              │
│   141 │                                                                      │
│   142 │   # Load the model in simple 16-bit mode by default                  │
│   143 │   if not any([shared.args.cpu, shared.args.load_in_8bit, shared.args │
│ ❱ 144 │   │   model = LoaderClass.from_pretrained(Path(f"{shared.args.model_ │
│   145 │   │   if torch.has_mps:                                              │
│   146 │   │   │   device = torch.device('mps')                               │
│   147 │   │   │   model = model.to(device)                                   │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factor │
│ y.py:484 in from_pretrained                                                  │
│                                                                              │
│   481 │   │   │   )                                                          │
│   482 │   │   elif type(config) in cls._model_mapping.keys():                │
│   483 │   │   │   model_class = _get_model_class(config, cls._model_mapping) │
│ ❱ 484 │   │   │   return model_class.from_pretrained(                        │
│   485 │   │   │   │   pretrained_model_name_or_path, *model_args, config=con │
│   486 │   │   │   )                                                          │
│   487 │   │   raise ValueError(                                              │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py:2449  │
│ in from_pretrained                                                           │
│                                                                              │
│   2446 │   │   │   │   │   │   " to load this model from those weights."     │
│   2447 │   │   │   │   │   )                                                 │
│   2448 │   │   │   │   else:                                                 │
│ ❱ 2449 │   │   │   │   │   raise EnvironmentError(                           │
│   2450 │   │   │   │   │   │   f"Error no file named {_add_variant(WEIGHTS_N │
│   2451 │   │   │   │   │   │   f" {TF_WEIGHTS_NAME + '.index'} or {FLAX_WEIG │
│   2452 │   │   │   │   │   │   f" {pretrained_model_name_or_path}."          │
╰──────────────────────────────────────────────────────────────────────────────╯
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or
flax_model.msgpack found in directory models/stable-vicuna-13B-GPTQ.

**Comment by camenduru** [comment]
Hi @Cabel7 👋 please try again

**Comment by Cabel7** [comment]
@camenduru
 (⁠✷⁠‿⁠✷⁠) It's working now 
![Screenshot_2023-07-12-13-34-13-17_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/camenduru/text-generation-webui-colab/assets/134921117/e69181cd-76ba-456e-b276-3cbc7ebac21b)
