### ISSUE TITLE
Endless queue

### ISSUE THREAD

**Issue by Katopr** [camenduru/text-generation-webui-colab#23]
After clicking the "Running on public URL" link on pygmalion 13b and 7b a queue starts that never ends
![pyg](https://github.com/camenduru/text-generation-webui-colab/assets/140808673/203bb567-6a7d-41c5-847d-47a64848c9fc)
![image](https://github.com/camenduru/text-generation-webui-colab/assets/140808673/aec909ea-fd97-449a-a20b-8be3aa8e66d1)

**Comment by camenduru** [comment]
thanks for the info ❤ please test new v2.3
