### ISSUE TITLE
cannot import name 'is_npu_available' from 'accelerate.utils' 

### ISSUE THREAD

**Issue by jackyzhang69** [camenduru/text-generation-webui-colab#24]
│ /usr/local/lib/python3.10/dist-packages/peft/utils/other.py:24 in <module>   │
│                                                                              │
│    21 import accelerate                                                      │
│    22 import torch                                                           │
│    23 from accelerate.hooks import add_hook_to_module, remove_hook_from_modu │
│ ❱  24 from accelerate.utils import is_npu_available, is_xpu_available        │
│    25                                                                        │
│    26 from ..import_utils import is_auto_gptq_available                      │
│    27                                                                        │
╰──────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name 'is_npu_available' from 'accelerate.utils' 
(/usr/local/lib/python3.10/dist-packages/accelerate/utils/__init__.py)

actually it is installed.

**Comment by XSES-0020** [comment]
try this. it might work ( •̀ ω •́ )✧
`pip install --upgrade accelerate`

**Comment by kyrie2to11** [comment]
> try this. it might work ( •̀ ω •́ )✧ `pip install --upgrade accelerate`

it works. thank u!

**Comment by Lyyynnnnnn** [comment]
I meet the same problem and can't deal with it.

**Comment by camenduru** [comment]
thanks for the info ❤ please test new v2.3

**Comment by liuzc188** [comment]
> 

well, you should use       pip install accelerate==0.21.0
PS: 0.22.0 version may be same error.
