### ISSUE TITLE
message repeat of characters 

### ISSUE THREAD

**Issue by vxxlfs** [camenduru/text-generation-webui-colab#31]
When talking with the bot, I have repeated messages, nothing helps, even changing the temperature and other settings. After updating I got this error. I use redmond puffin 13b. Any help please? or advice

**Comment by camenduru** [comment]
please try instruction_template: `Alpaca`

![Screenshot 2023-08-28 165206](https://github.com/camenduru/text-generation-webui-colab/assets/54370274/7f619737-eb3e-4368-9b03-65836d1207f0)

**Comment by vxxlfs** [comment]
> please try instruction_template: `Alpaca`
> 
> ![Screenshot 2023-08-28 165206](https://user-images.githubusercontent.com/54370274/263722905-7f619737-eb3e-4368-9b03-65836d1207f0.png)

Thanks so much, working. If any problem or bug appears again, I will let you know. Thank you for the work that you do all this and do not forget about colab
