### ISSUE TITLE
pyg7b and other models stop work

### ISSUE THREAD

**Issue by Samogub** [camenduru/text-generation-webui-colab#5]
5.5.2023 everything is okey, now i have this error. pyg7b model.

╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /content/text-generation-webui/server.py:927 in <module>                     │
│                                                                              │
│   924 │   │   })                                                             │
│   925 │                                                                      │
│   926 │   # Launch the web UI                                                │
│ ❱ 927 │   create_interface()                                                 │
│   928 │   while True:                                                        │
│   929 │   │   time.sleep(0.5)                                                │
│   930 │   │   if shared.need_restart:                                        │
│                                                                              │
│ /content/text-generation-webui/server.py:514 in create_interface             │
│                                                                              │
│   511 │   if shared.args.extensions is not None and len(shared.args.extensio │
│   512 │   │   extensions_module.load_extensions()                            │
│   513 │                                                                      │
│ ❱ 514 │   with gr.Blocks(css=ui.css if not shared.is_chat() else ui.css + ui │
│   515 │   │                                                                  │
│   516 │   │   # Create chat mode interface                                   │
│   517 │   │   if shared.is_chat():                                           │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/gradio/blocks.py:1285 in __exit__    │
│                                                                              │
│   1282 │   │   │   Context.root_block = None                                 │
│   1283 │   │   else:                                                         │
│   1284 │   │   │   self.parent.children.extend(self.children)                │
│ ❱ 1285 │   │   self.config = self.get_config_file()                          │
│   1286 │   │   self.app = routes.App.create_app(self)                        │
│   1287 │   │   self.progress_tracking = any(block_fn.tracks_progress for blo │
│   1288 │   │   self.exited = True                                            │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/gradio/blocks.py:1261 in             │
│ get_config_file                                                              │
│                                                                              │
│   1258 │   │   │   │   assert isinstance(block, serializing.Serializable)    │
│   1259 │   │   │   │   block_config["serializer"] = serializer               │
│   1260 │   │   │   │   block_config["info"] = {                              │
│ ❱ 1261 │   │   │   │   │   "input": list(block.input_api_info()),  # type: i │
│   1262 │   │   │   │   │   "output": list(block.output_api_info()),  # type: │
│   1263 │   │   │   │   }                                                     │
│   1264 │   │   │   config["components"].append(block_config)                 │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/gradio_client/serializing.py:40 in   │
│ input_api_info                                                               │
│                                                                              │
│    37 │   # For backwards compatibility                                      │
│    38 │   def input_api_info(self) -> tuple[str, str]:                       │
│    39 │   │   api_info = self.api_info()                                     │
│ ❱  40 │   │   return (api_info["serialized_input"][0], api_info["serialized_ │
│    41 │                                                                      │
│    42 │   # For backwards compatibility                                      │
│    43 │   def output_api_info(self) -> tuple[str, str]:                      │
╰──────────────────────────────────────────────────────────────────────────────╯
KeyError: 'serialized_input'

and here is vicuna-13B-GPTQ
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /content/text-generation-webui/server.py:591 in <module>                     │
│                                                                              │
│   588 │   │   shared.gradio['interface'].launch(prevent_thread_lock=True, sh │
│   589                                                                        │
│   590                                                                        │
│ ❱ 591 create_interface()                                                     │
│   592                                                                        │
│   593 while True:                                                            │
│   594 │   time.sleep(0.5)                                                    │
│                                                                              │
│ /content/text-generation-webui/server.py:320 in create_interface             │
│                                                                              │
│   317 │   if shared.args.extensions is not None and len(shared.args.extensio │
│   318 │   │   extensions_module.load_extensions()                            │
│   319 │                                                                      │
│ ❱ 320 │   with gr.Blocks(css=ui.css if not shared.is_chat() else ui.css + ui │
│   321 │   │   if shared.is_chat():                                           │
│   322 │   │   │   shared.gradio['Chat input'] = gr.State()                   │
│   323 │   │   │   with gr.Tab("Text generation", elem_id="main"):            │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/gradio/blocks.py:1200 in __exit__    │
│                                                                              │
│   1197 │   │   │   Context.root_block = None                                 │
│   1198 │   │   else:                                                         │
│   1199 │   │   │   self.parent.children.extend(self.children)                │
│ ❱ 1200 │   │   self.config = self.get_config_file()                          │
│   1201 │   │   self.app = routes.App.create_app(self)                        │
│   1202 │   │   self.progress_tracking = any(block_fn.tracks_progress for blo │
│   1203 │   │   self.exited = True                                            │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/gradio/blocks.py:1176 in             │
│ get_config_file                                                              │
│                                                                              │
│   1173 │   │   │   │   assert isinstance(block, serializing.Serializable)    │
│   1174 │   │   │   │   block_config["serializer"] = serializer               │
│   1175 │   │   │   │   block_config["info"] = {                              │
│ ❱ 1176 │   │   │   │   │   "input": list(block.input_api_info()),  # type: i │
│   1177 │   │   │   │   │   "output": list(block.output_api_info()),  # type: │
│   1178 │   │   │   │   }                                                     │
│   1179 │   │   │   config["components"].append(block_config)                 │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/gradio_client/serializing.py:40 in   │
│ input_api_info                                                               │
│                                                                              │
│    37 │   # For backwards compatibility                                      │
│    38 │   def input_api_info(self) -> tuple[str, str]:                       │
│    39 │   │   api_info = self.api_info()                                     │
│ ❱  40 │   │   return (api_info["serialized_input"][0], api_info["serialized_ │
│    41 │                                                                      │
│    42 │   # For backwards compatibility                                      │
│    43 │   def output_api_info(self) -> tuple[str, str]:                      │
╰──────────────────────────────────────────────────────────────────────────────╯
KeyError: 'serialized_input'

**Comment by Samogub** [comment]
i fixed this issue, just need add !pip install --force gradio==3.28.3 after !pip install -r requirements.txt


> %cd /content/text-generation-webui
!pip install -r requirements.txt
!pip install --force gradio==3.28.3

i will close it later.

**Comment by camenduru** [comment]
thanks @Samogub ❤
